CREATE TABLE sys_config_send(
    id SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    counter_id SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    win_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    total_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    send_id SMALLINT UNSIGNED NOT NULL,
    send_num MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    postdate_start DATE NOT NULL,
    postdate_end DATE NOT NULL
);


CREATE TABLE sys_config_counter(
    id SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    `type_id` TINYINT UNSIGNED NOT NULL,
    quantity MEDIUMINT UNSIGNED NOT NULL
);

CREATE TABLE temp_orders(
    orderno VARCHAR(10) NOT NULL PRIMARY KEY,
    `status` TINYINT UNSIGNED NOT NULL,
    xml VARCHAR(400) NOT NULL,
    posttime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE activity_login_send(
    uid INT UNSIGNED NOT NULL PRIMARY KEY,
    days TINYINT UNSIGNED NOT NULL DEFAULT 1,
    is_send BIT NOT NULL DEFAULT 0,
    posttime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE activity_send(
    id INT UNSIGNED NOT NULL PRIMARY KEY,
    uid INT UNSIGNED NOT NULL,
    send_id SMALLINT UNSIGNED NOT NULL,
    send_num MEDIUMINT UNSIGNED NOT NULL DEFAULT 0,
    activity_send_id SMALLINT UNSIGNED NOT NULL,
    postdate DATE NOT NULL DEFAULT cur_date(,
    posttime TIME NOT NULL NOW()
);
